### ISSUE TITLE
cdutil forces python 3

### ISSUE THREAD

**Issue by doutriaux1** [CDAT/cdutil#26]

**Comment by doutriaux1** [comment]
```
conda create -n pmp_mar19 -c uvcdat/label/nightly -c conda-forge -c uvcdat -c pcmdi/label/nightly -c pcmdi vcs vcsaddons pcmdi_metrics cia)
```
 
leads to:

```
>>> import cdp
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/export_backup/gleckler1/anaconda2/envs/pmp_apr04/lib/python3.6/site-packages/cdp/__init__.py", line 8, in <module>
    from . import cdp_parser
  File "/export_backup/gleckler1/anaconda2/envs/pmp_apr04/lib/python3.6/site-packages/cdp/cdp_parser.py", line 13, in <module>
    import StringIO
ModuleNotFoundError: No module named 'StringIO'
```

**Comment by dnadeau4** [comment]
@doutriaux1 this is the wrong repo for this CDP issue.

**Comment by dnadeau4** [comment]
@doutriaux1 can you close?
